export const connectorUpdateResources = {
  es: { connectorUpdates: {
    current: "Actualizado", checking: "Comprobando actualizaciones", available: "Actualización disponible", waiting: "Esperando a que el equipo esté libre", downloading: "Descargando actualización", installing: "Instalando y verificando", failed: "La actualización necesita atención", manual: "Actualización inicial necesaria", paused: "Actualización pospuesta", offline: "Se aplicará cuando el equipo se conecte",
    automatic: "Actualizar automáticamente cuando el equipo esté libre", now: "Actualizar ahora", postpone: "Posponer 24 horas", target: "Versión disponible: {{version}}", saved: "Preferencia guardada. El equipo la recibirá al conectarse; se respetarán las tareas y los chats temporales abiertos.", error: "No se pudo guardar. Inténtalo de nuevo.",
    bootstrap: "Actualiza una vez desde ese equipo para habilitar estos controles. En la app Agent Control, elige Actualizar; en instalaciones de terminal, usa el actualizador instalado.", onboarding: "Las actualizaciones automáticas se activan cuando el equipo está libre. Puedes desactivarlas o posponerlas en Mis equipos.", checkComputer: "Revisar la actualización en Mis equipos",
    reasons: { busy: "Hay tareas activas o pendientes de confirmar.", temporary: "Cierra los chats temporales cuando termines para permitir la actualización.", offline: "Mantén el equipo encendido y conectado.", recovery: "Abre el actualizador en ese equipo para recuperar la operación pendiente.", verification: "No se pudo verificar la actualización. Revisa el diagnóstico en ese equipo.", service: "Revisa los permisos del servicio en ese equipo.", rollout: "Esta versión se está distribuyendo gradualmente.", unsupported: "Esta instalación requiere una actualización local inicial.", externalHermes: "Tu instalación de Hermes se administra por separado." },
  } },
  en: { connectorUpdates: {
    current: "Up to date", checking: "Checking for updates", available: "Update available", waiting: "Waiting for the computer to be idle", downloading: "Downloading update", installing: "Installing and verifying", failed: "Update needs attention", manual: "Initial update required", paused: "Update postponed", offline: "Will apply when the computer connects",
    automatic: "Update automatically when the computer is idle", now: "Update now", postpone: "Postpone 24 hours", target: "Available version: {{version}}", saved: "Preference saved. The computer will receive it when connected; active work and open temporary chats will be preserved.", error: "Could not save. Please try again.",
    bootstrap: "Update once on this computer to enable these controls. Choose Update in the Agent Control app; for terminal installations, use the installed updater.", onboarding: "Automatic updates run when the computer is idle. You can turn them off or postpone them in My computers.", checkComputer: "Check the update in My computers",
    reasons: { busy: "There is active work or work awaiting confirmation.", temporary: "Close temporary chats when you are finished to allow the update.", offline: "Keep the computer awake and connected.", recovery: "Open the updater on this computer to recover the pending operation.", verification: "The update could not be verified. Check diagnostics on this computer.", service: "Check service permissions on this computer.", rollout: "This version is being rolled out gradually.", unsupported: "This installation needs an initial local update.", externalHermes: "Your Hermes installation is managed separately." },
  } },
  fr: { connectorUpdates: {
    current: "À jour", checking: "Recherche de mises à jour", available: "Mise à jour disponible", waiting: "En attente d’un ordinateur inactif", downloading: "Téléchargement", installing: "Installation et vérification", failed: "La mise à jour nécessite une intervention", manual: "Mise à jour initiale requise", paused: "Mise à jour reportée", offline: "S’appliquera lorsque l’ordinateur sera connecté",
    automatic: "Mettre à jour automatiquement lorsque l’ordinateur est inactif", now: "Mettre à jour", postpone: "Reporter de 24 heures", target: "Version disponible : {{version}}", saved: "Préférence enregistrée. Elle sera transmise à la connexion ; les tâches et les conversations temporaires ouvertes seront préservées.", error: "Enregistrement impossible. Réessayez.",
    bootstrap: "Effectuez une première mise à jour sur cet ordinateur. Choisissez Mettre à jour dans Agent Control ou utilisez l’utilitaire installé pour une installation en terminal.", onboarding: "Les mises à jour automatiques attendent que l’ordinateur soit inactif. Vous pouvez les désactiver ou les reporter dans Mes ordinateurs.", checkComputer: "Vérifier la mise à jour dans Mes ordinateurs",
    reasons: { busy: "Des tâches sont actives ou en attente de confirmation.", temporary: "Fermez les conversations temporaires une fois terminées pour autoriser la mise à jour.", offline: "Gardez l’ordinateur allumé et connecté.", recovery: "Ouvrez l’utilitaire de mise à jour pour récupérer l’opération en attente.", verification: "La mise à jour n’a pas pu être vérifiée. Consultez le diagnostic sur cet ordinateur.", service: "Vérifiez les autorisations du service.", rollout: "Cette version est distribuée progressivement.", unsupported: "Une première mise à jour locale est nécessaire.", externalHermes: "Votre installation Hermes est gérée séparément." },
  } },
  de: { connectorUpdates: {
    current: "Aktuell", checking: "Updates werden geprüft", available: "Update verfügbar", waiting: "Wartet, bis der Computer frei ist", downloading: "Update wird heruntergeladen", installing: "Installation und Prüfung", failed: "Update erfordert Aufmerksamkeit", manual: "Erstes Update erforderlich", paused: "Update verschoben", offline: "Wird bei der nächsten Verbindung angewendet",
    automatic: "Automatisch aktualisieren, wenn der Computer frei ist", now: "Jetzt aktualisieren", postpone: "24 Stunden verschieben", target: "Verfügbare Version: {{version}}", saved: "Einstellung gespeichert. Sie wird bei der nächsten Verbindung übertragen; laufende Aufgaben und offene temporäre Chats bleiben erhalten.", error: "Speichern fehlgeschlagen. Bitte erneut versuchen.",
    bootstrap: "Aktualisieren Sie einmal auf diesem Computer. Wählen Sie Aktualisieren in Agent Control oder verwenden Sie bei Terminalinstallationen das installierte Updateprogramm.", onboarding: "Automatische Updates warten, bis der Computer frei ist. Unter Meine Computer können Sie sie deaktivieren oder verschieben.", checkComputer: "Update unter Meine Computer prüfen",
    reasons: { busy: "Aufgaben laufen oder warten auf Bestätigung.", temporary: "Schließen Sie temporäre Chats nach Abschluss, um das Update zu ermöglichen.", offline: "Lassen Sie den Computer eingeschaltet und verbunden.", recovery: "Öffnen Sie das Updateprogramm, um den ausstehenden Vorgang wiederherzustellen.", verification: "Das Update konnte nicht geprüft werden. Prüfen Sie die Diagnose auf diesem Computer.", service: "Prüfen Sie die Dienstberechtigungen.", rollout: "Diese Version wird schrittweise verteilt.", unsupported: "Diese Installation benötigt ein erstes lokales Update.", externalHermes: "Ihre Hermes-Installation wird separat verwaltet." },
  } },
  pt: { connectorUpdates: {
    current: "Atualizado", checking: "A procurar atualizações", available: "Atualização disponível", waiting: "À espera de o computador ficar livre", downloading: "A transferir atualização", installing: "A instalar e verificar", failed: "A atualização precisa de atenção", manual: "Atualização inicial necessária", paused: "Atualização adiada", offline: "Será aplicada quando o computador se ligar",
    automatic: "Atualizar automaticamente quando o computador estiver livre", now: "Atualizar agora", postpone: "Adiar 24 horas", target: "Versão disponível: {{version}}", saved: "Preferência guardada. Será recebida quando o computador se ligar; as tarefas e conversas temporárias abertas serão preservadas.", error: "Não foi possível guardar. Tente novamente.",
    bootstrap: "Atualize uma vez neste computador para ativar estes controlos. Escolha Atualizar na aplicação Agent Control ou use o atualizador instalado nas instalações de terminal.", onboarding: "As atualizações automáticas esperam que o computador esteja livre. Pode desativá-las ou adiá-las em Meus computadores.", checkComputer: "Verificar a atualização em Meus computadores",
    reasons: { busy: "Existem tarefas ativas ou por confirmar.", temporary: "Feche as conversas temporárias quando terminar para permitir a atualização.", offline: "Mantenha o computador ligado e conectado.", recovery: "Abra o atualizador neste computador para recuperar a operação pendente.", verification: "Não foi possível verificar a atualização. Consulte o diagnóstico neste computador.", service: "Verifique as permissões do serviço.", rollout: "Esta versão está a ser distribuída gradualmente.", unsupported: "Esta instalação precisa de uma atualização local inicial.", externalHermes: "A sua instalação do Hermes é gerida separadamente." },
  } },
} as const;
