export const dictationResources = {
  es: { dictation: {
    start: "Dictar por voz", stop: "Detener dictado", connecting: "Activando micrófono…", listening: "Escuchando…", stopping: "Terminando transcripción…", provisional: "Transcripción provisional: {{text}}", disclosure: "El audio se envía a ElevenLabs con un token temporal; revisa el texto antes de enviarlo.", consentTitle: "Activar dictado por voz", consentDescription: "Antes de encender el micrófono, confirma cómo funciona el dictado.", consentAudio: "El audio se envía directamente a ElevenLabs con un token temporal.", consentRetention: "La conservación y el uso del audio se rigen por tu cuenta y los términos de ElevenLabs.", consentDraft: "Solo el texto confirmado se añade a tu borrador editable; nunca se envía automáticamente al agente.", consentCancel: "Ahora no", consentAccept: "Aceptar y activar micrófono", consentClose: "Cerrar información del dictado",
    permissionDenied: "No se concedió acceso al micrófono. Habilítalo en los permisos del navegador.", quota: "ElevenLabs no tiene cuota disponible o limitó la solicitud.", network: "Se perdió la conexión durante el dictado.", auth: "No se pudo autorizar el dictado. Revisa tu integración de ElevenLabs.", unavailable: "El dictado no está disponible en este navegador.", tooLong: "El segmento dictado era demasiado largo y se descartó.", unconfirmed: "No se pudieron confirmar las últimas palabras. Intenta dictarlas de nuevo.", generic: "No se pudo iniciar el dictado.",
  } },
  en: { dictation: {
    start: "Dictate by voice", stop: "Stop dictation", connecting: "Starting microphone…", listening: "Listening…", stopping: "Finishing transcription…", provisional: "Provisional transcript: {{text}}", disclosure: "Audio is sent to ElevenLabs with a temporary token; review the text before sending.", consentTitle: "Enable voice dictation", consentDescription: "Before turning on the microphone, confirm how dictation works.", consentAudio: "Audio is sent directly to ElevenLabs with a temporary token.", consentRetention: "Audio retention and use are governed by your ElevenLabs account and terms.", consentDraft: "Only confirmed text is added to your editable draft; it is never sent to the agent automatically.", consentCancel: "Not now", consentAccept: "Accept and enable microphone", consentClose: "Close dictation information",
    permissionDenied: "Microphone access was not granted. Enable it in your browser permissions.", quota: "ElevenLabs has no available quota or rate-limited the request.", network: "The connection was lost during dictation.", auth: "Dictation could not be authorized. Check your ElevenLabs integration.", unavailable: "Dictation is not available in this browser.", tooLong: "The dictated segment was too long and was discarded.", unconfirmed: "The last words could not be confirmed. Try dictating them again.", generic: "Dictation could not be started.",
  } },
  fr: { dictation: {
    start: "Dicter à la voix", stop: "Arrêter la dictée", connecting: "Activation du microphone…", listening: "Écoute…", stopping: "Finalisation de la transcription…", provisional: "Transcription provisoire : {{text}}", disclosure: "L’audio est envoyé à ElevenLabs avec un jeton temporaire ; vérifiez le texte avant de l’envoyer.", consentTitle: "Activer la dictée vocale", consentDescription: "Avant d’activer le microphone, confirmez le fonctionnement de la dictée.", consentAudio: "L’audio est envoyé directement à ElevenLabs avec un jeton temporaire.", consentRetention: "La conservation et l’utilisation de l’audio sont régies par votre compte et les conditions d’ElevenLabs.", consentDraft: "Seul le texte confirmé est ajouté à votre brouillon modifiable ; il n’est jamais envoyé automatiquement à l’agent.", consentCancel: "Pas maintenant", consentAccept: "Accepter et activer le microphone", consentClose: "Fermer les informations sur la dictée",
    permissionDenied: "L’accès au microphone n’a pas été accordé. Autorisez-le dans les permissions du navigateur.", quota: "ElevenLabs n’a plus de quota disponible ou a limité la requête.", network: "La connexion a été perdue pendant la dictée.", auth: "La dictée n’a pas pu être autorisée. Vérifiez votre intégration ElevenLabs.", unavailable: "La dictée n’est pas disponible dans ce navigateur.", tooLong: "Le segment dicté était trop long et a été ignoré.", unconfirmed: "Les derniers mots n’ont pas pu être confirmés. Essayez de les dicter à nouveau.", generic: "Impossible de démarrer la dictée.",
  } },
  de: { dictation: {
    start: "Per Sprache diktieren", stop: "Diktat beenden", connecting: "Mikrofon wird aktiviert…", listening: "Hört zu…", stopping: "Transkription wird abgeschlossen…", provisional: "Vorläufiges Transkript: {{text}}", disclosure: "Audio wird mit einem temporären Token an ElevenLabs gesendet; prüfe den Text vor dem Senden.", consentTitle: "Sprachdiktat aktivieren", consentDescription: "Bestätige vor dem Einschalten des Mikrofons, wie das Diktat funktioniert.", consentAudio: "Audio wird mit einem temporären Token direkt an ElevenLabs gesendet.", consentRetention: "Speicherung und Nutzung des Audios richten sich nach deinem ElevenLabs-Konto und dessen Bedingungen.", consentDraft: "Nur bestätigter Text wird deinem bearbeitbaren Entwurf hinzugefügt; er wird nie automatisch an den Agenten gesendet.", consentCancel: "Jetzt nicht", consentAccept: "Akzeptieren und Mikrofon aktivieren", consentClose: "Diktierinformationen schließen",
    permissionDenied: "Der Mikrofonzugriff wurde nicht erteilt. Aktiviere ihn in den Browserberechtigungen.", quota: "ElevenLabs hat kein verfügbares Kontingent oder hat die Anfrage begrenzt.", network: "Die Verbindung wurde während des Diktats unterbrochen.", auth: "Das Diktat konnte nicht autorisiert werden. Prüfe deine ElevenLabs-Integration.", unavailable: "Die Diktierfunktion ist in diesem Browser nicht verfügbar.", tooLong: "Das diktierte Segment war zu lang und wurde verworfen.", unconfirmed: "Die letzten Wörter konnten nicht bestätigt werden. Diktiere sie bitte erneut.", generic: "Das Diktat konnte nicht gestartet werden.",
  } },
  pt: { dictation: {
    start: "Ditar por voz", stop: "Parar ditado", connecting: "Ativando microfone…", listening: "Ouvindo…", stopping: "Finalizando transcrição…", provisional: "Transcrição provisória: {{text}}", disclosure: "O áudio é enviado à ElevenLabs com um token temporário; revise o texto antes de enviar.", consentTitle: "Ativar ditado por voz", consentDescription: "Antes de ligar o microfone, confirme como o ditado funciona.", consentAudio: "O áudio é enviado diretamente à ElevenLabs com um token temporário.", consentRetention: "A retenção e o uso do áudio são regidos pela sua conta e pelos termos da ElevenLabs.", consentDraft: "Somente o texto confirmado é adicionado ao rascunho editável; ele nunca é enviado automaticamente ao agente.", consentCancel: "Agora não", consentAccept: "Aceitar e ativar microfone", consentClose: "Fechar informações do ditado",
    permissionDenied: "O acesso ao microfone não foi concedido. Ative-o nas permissões do navegador.", quota: "A ElevenLabs não tem cota disponível ou limitou a solicitação.", network: "A conexão foi perdida durante o ditado.", auth: "Não foi possível autorizar o ditado. Verifique sua integração da ElevenLabs.", unavailable: "O ditado não está disponível neste navegador.", tooLong: "O segmento ditado era muito longo e foi descartado.", unconfirmed: "Não foi possível confirmar as últimas palavras. Tente ditá-las novamente.", generic: "Não foi possível iniciar o ditado.",
  } },
} as const;
