export const dictationResources = {
  es: { dictation: {
    privacyTitle: "Privacidad", privacyDescription: "Cómo se usa el audio y el texto en las funciones de voz.",
    paused: "Dictado en pausa", pause: "Pausar dictado", resume: "Reanudar dictado",
    start: "Dictar por voz", stop: "Detener dictado", connecting: "Activando micrófono…", listening: "Escuchando…", stopping: "Terminando transcripción…", provisional: "Transcripción provisional: {{text}}", privacyAudio: "El audio se envía directamente a ElevenLabs con un token temporal.", privacyRetention: "La conservación y el uso del audio se rigen por tu cuenta y los términos de ElevenLabs.", privacyDraft: "Solo el texto confirmado se añade a tu borrador editable; nunca se envía automáticamente al agente.",
    permissionDenied: "No se concedió acceso al micrófono. Habilítalo en los permisos del navegador.", quota: "ElevenLabs no tiene cuota disponible o limitó la solicitud.", network: "Se perdió la conexión durante el dictado.", auth: "No se pudo autorizar el dictado. Revisa tu integración de ElevenLabs.", unavailable: "El dictado no está disponible en este navegador.", tooLong: "El segmento dictado era demasiado largo y se descartó.", unconfirmed: "No se pudieron confirmar las últimas palabras. Intenta dictarlas de nuevo.", generic: "No se pudo iniciar el dictado.",
  } },
  en: { dictation: {
    privacyTitle: "Privacy", privacyDescription: "How audio and text are used in voice features.",
    paused: "Dictation paused", pause: "Pause dictation", resume: "Resume dictation",
    start: "Dictate by voice", stop: "Stop dictation", connecting: "Starting microphone…", listening: "Listening…", stopping: "Finishing transcription…", provisional: "Provisional transcript: {{text}}", privacyAudio: "Audio is sent directly to ElevenLabs with a temporary token.", privacyRetention: "Audio retention and use are governed by your ElevenLabs account and terms.", privacyDraft: "Only confirmed text is added to your editable draft; it is never sent to the agent automatically.",
    permissionDenied: "Microphone access was not granted. Enable it in your browser permissions.", quota: "ElevenLabs has no available quota or rate-limited the request.", network: "The connection was lost during dictation.", auth: "Dictation could not be authorized. Check your ElevenLabs integration.", unavailable: "Dictation is not available in this browser.", tooLong: "The dictated segment was too long and was discarded.", unconfirmed: "The last words could not be confirmed. Try dictating them again.", generic: "Dictation could not be started.",
  } },
  fr: { dictation: {
    privacyTitle: "Confidentialité", privacyDescription: "Utilisation de l’audio et du texte dans les fonctions vocales.",
    paused: "Dictée en pause", pause: "Mettre la dictée en pause", resume: "Reprendre la dictée",
    start: "Dicter à la voix", stop: "Arrêter la dictée", connecting: "Activation du microphone…", listening: "Écoute…", stopping: "Finalisation de la transcription…", provisional: "Transcription provisoire : {{text}}", privacyAudio: "L’audio est envoyé directement à ElevenLabs avec un jeton temporaire.", privacyRetention: "La conservation et l’utilisation de l’audio sont régies par votre compte et les conditions d’ElevenLabs.", privacyDraft: "Seul le texte confirmé est ajouté à votre brouillon modifiable ; il n’est jamais envoyé automatiquement à l’agent.",
    permissionDenied: "L’accès au microphone n’a pas été accordé. Autorisez-le dans les permissions du navigateur.", quota: "ElevenLabs n’a plus de quota disponible ou a limité la requête.", network: "La connexion a été perdue pendant la dictée.", auth: "La dictée n’a pas pu être autorisée. Vérifiez votre intégration ElevenLabs.", unavailable: "La dictée n’est pas disponible dans ce navigateur.", tooLong: "Le segment dicté était trop long et a été ignoré.", unconfirmed: "Les derniers mots n’ont pas pu être confirmés. Essayez de les dicter à nouveau.", generic: "Impossible de démarrer la dictée.",
  } },
  de: { dictation: {
    privacyTitle: "Datenschutz", privacyDescription: "So werden Audio und Text in Sprachfunktionen verwendet.",
    paused: "Diktat pausiert", pause: "Diktat pausieren", resume: "Diktat fortsetzen",
    start: "Per Sprache diktieren", stop: "Diktat beenden", connecting: "Mikrofon wird aktiviert…", listening: "Hört zu…", stopping: "Transkription wird abgeschlossen…", provisional: "Vorläufiges Transkript: {{text}}", privacyAudio: "Audio wird mit einem temporären Token direkt an ElevenLabs gesendet.", privacyRetention: "Speicherung und Nutzung des Audios richten sich nach deinem ElevenLabs-Konto und dessen Bedingungen.", privacyDraft: "Nur bestätigter Text wird deinem bearbeitbaren Entwurf hinzugefügt; er wird nie automatisch an den Agenten gesendet.",
    permissionDenied: "Der Mikrofonzugriff wurde nicht erteilt. Aktiviere ihn in den Browserberechtigungen.", quota: "ElevenLabs hat kein verfügbares Kontingent oder hat die Anfrage begrenzt.", network: "Die Verbindung wurde während des Diktats unterbrochen.", auth: "Das Diktat konnte nicht autorisiert werden. Prüfe deine ElevenLabs-Integration.", unavailable: "Die Diktierfunktion ist in diesem Browser nicht verfügbar.", tooLong: "Das diktierte Segment war zu lang und wurde verworfen.", unconfirmed: "Die letzten Wörter konnten nicht bestätigt werden. Diktiere sie bitte erneut.", generic: "Das Diktat konnte nicht gestartet werden.",
  } },
  pt: { dictation: {
    privacyTitle: "Privacidade", privacyDescription: "Como o áudio e o texto são usados nas funções de voz.",
    paused: "Ditado em pausa", pause: "Pausar ditado", resume: "Retomar ditado",
    start: "Ditar por voz", stop: "Parar ditado", connecting: "Ativando microfone…", listening: "Ouvindo…", stopping: "Finalizando transcrição…", provisional: "Transcrição provisória: {{text}}", privacyAudio: "O áudio é enviado diretamente à ElevenLabs com um token temporário.", privacyRetention: "A retenção e o uso do áudio são regidos pela sua conta e pelos termos da ElevenLabs.", privacyDraft: "Somente o texto confirmado é adicionado ao rascunho editável; ele nunca é enviado automaticamente ao agente.",
    permissionDenied: "O acesso ao microfone não foi concedido. Ative-o nas permissões do navegador.", quota: "A ElevenLabs não tem cota disponível ou limitou a solicitação.", network: "A conexão foi perdida durante o ditado.", auth: "Não foi possível autorizar o ditado. Verifique sua integração da ElevenLabs.", unavailable: "O ditado não está disponível neste navegador.", tooLong: "O segmento ditado era muito longo e foi descartado.", unconfirmed: "Não foi possível confirmar as últimas palavras. Tente ditá-las novamente.", generic: "Não foi possível iniciar o ditado.",
  } },
} as const;
