export const integrationResources = {
  es: { integrations: {
    title: "Integraciones", description: "Conecta tu propia cuenta de ElevenLabs para activar el dictado.", loading: "Consultando…", configured: "Configurado", notConfigured: "Sin configurar",
    autoLanguage: "idioma automático", apiKey: "API key de ElevenLabs", replaceKey: "Reemplazar API key", keyPlaceholder: "Pega una API key", keyConfiguredPlaceholder: "Configurada · escribe para reemplazar", writeOnlyHint: "La clave se envía una vez a Agent Control para cifrarse; no se guarda en este dispositivo ni vuelve en las respuestas.",
    audioDisclosure: "Al dictar, el audio se envía directamente a ElevenLabs con un token temporal. La API key permanece en el backend.", nativeFallback: "Sin configurar ElevenLabs, puedes seguir usando el dictado nativo del teclado de tu móvil.", save: "Guardar cifrada", replace: "Reemplazar clave", saving: "Guardando…", test: "Probar conexión", testing: "Probando…", delete: "Eliminar clave", deleting: "Eliminando…", cancel: "Cancelar", confirmDelete: "Eliminar", deleteConfirm: "¿Eliminar tu clave de ElevenLabs? El dictado dejará de estar disponible.",
    saved: "Clave guardada. El dictado ya está disponible.", testPassed: "Conexión verificada correctamente.", deleted: "Clave eliminada. El dictado quedó desactivado.", loadError: "No se pudo consultar la integración.", saveError: "No se pudo guardar la clave. El campo se vació por seguridad.", testFailed: "ElevenLabs rechazó la prueba o no respondió.", deleteError: "No se pudo eliminar la clave.", offline: "Reconéctate para administrar esta integración.",
  } },
  en: { integrations: {
    title: "Integrations", description: "Connect your own ElevenLabs account to enable dictation.", loading: "Checking…", configured: "Configured", notConfigured: "Not configured",
    autoLanguage: "automatic language", apiKey: "ElevenLabs API key", replaceKey: "Replace API key", keyPlaceholder: "Paste an API key", keyConfiguredPlaceholder: "Configured · type to replace", writeOnlyHint: "The key is sent once to Agent Control for encryption; it is not stored on this device or returned in responses.",
    audioDisclosure: "While dictating, audio is sent directly to ElevenLabs with a temporary token. The API key remains in the backend.", nativeFallback: "Without configuring ElevenLabs, you can still use your mobile keyboard’s built-in dictation.", save: "Save encrypted", replace: "Replace key", saving: "Saving…", test: "Test connection", testing: "Testing…", delete: "Delete key", deleting: "Deleting…", cancel: "Cancel", confirmDelete: "Delete", deleteConfirm: "Delete your ElevenLabs key? Dictation will no longer be available.",
    saved: "Key saved. Dictation is now available.", testPassed: "Connection verified successfully.", deleted: "Key deleted. Dictation is now disabled.", loadError: "The integration could not be loaded.", saveError: "The key could not be saved. The field was cleared for safety.", testFailed: "ElevenLabs rejected the test or did not respond.", deleteError: "The key could not be deleted.", offline: "Reconnect to manage this integration.",
  } },
  fr: { integrations: {
    title: "Intégrations", description: "Connectez votre propre compte ElevenLabs pour activer la dictée.", loading: "Vérification…", configured: "Configuré", notConfigured: "Non configuré",
    autoLanguage: "langue automatique", apiKey: "Clé API ElevenLabs", replaceKey: "Remplacer la clé API", keyPlaceholder: "Collez une clé API", keyConfiguredPlaceholder: "Configurée · saisissez pour remplacer", writeOnlyHint: "La clé est envoyée une seule fois à Agent Control pour être chiffrée ; elle n’est ni stockée sur cet appareil ni renvoyée dans les réponses.",
    audioDisclosure: "Pendant la dictée, l’audio est envoyé directement à ElevenLabs avec un jeton temporaire. La clé API reste dans le backend.", nativeFallback: "Sans configurer ElevenLabs, vous pouvez continuer à utiliser la dictée intégrée au clavier de votre mobile.", save: "Enregistrer chiffrée", replace: "Remplacer la clé", saving: "Enregistrement…", test: "Tester la connexion", testing: "Test…", delete: "Supprimer la clé", deleting: "Suppression…", cancel: "Annuler", confirmDelete: "Supprimer", deleteConfirm: "Supprimer votre clé ElevenLabs ? La dictée ne sera plus disponible.",
    saved: "Clé enregistrée. La dictée est maintenant disponible.", testPassed: "Connexion vérifiée avec succès.", deleted: "Clé supprimée. La dictée est désactivée.", loadError: "Impossible de charger l’intégration.", saveError: "Impossible d’enregistrer la clé. Le champ a été effacé par sécurité.", testFailed: "ElevenLabs a refusé le test ou n’a pas répondu.", deleteError: "Impossible de supprimer la clé.", offline: "Reconnectez-vous pour gérer cette intégration.",
  } },
  de: { integrations: {
    title: "Integrationen", description: "Verbinde dein eigenes ElevenLabs-Konto, um die Diktierfunktion zu aktivieren.", loading: "Wird geprüft…", configured: "Konfiguriert", notConfigured: "Nicht konfiguriert",
    autoLanguage: "automatische Sprache", apiKey: "ElevenLabs-API-Schlüssel", replaceKey: "API-Schlüssel ersetzen", keyPlaceholder: "API-Schlüssel einfügen", keyConfiguredPlaceholder: "Konfiguriert · zum Ersetzen eingeben", writeOnlyHint: "Der Schlüssel wird einmalig zur Verschlüsselung an Agent Control gesendet; er wird weder auf diesem Gerät gespeichert noch in Antworten zurückgegeben.",
    audioDisclosure: "Beim Diktieren wird Audio mit einem temporären Token direkt an ElevenLabs gesendet. Der API-Schlüssel bleibt im Backend.", nativeFallback: "Ohne ElevenLabs einzurichten, kannst du weiterhin die integrierte Diktierfunktion deiner mobilen Tastatur verwenden.", save: "Verschlüsselt speichern", replace: "Schlüssel ersetzen", saving: "Wird gespeichert…", test: "Verbindung testen", testing: "Wird getestet…", delete: "Schlüssel löschen", deleting: "Wird gelöscht…", cancel: "Abbrechen", confirmDelete: "Löschen", deleteConfirm: "Deinen ElevenLabs-Schlüssel löschen? Die Diktierfunktion ist danach nicht mehr verfügbar.",
    saved: "Schlüssel gespeichert. Die Diktierfunktion ist jetzt verfügbar.", testPassed: "Verbindung erfolgreich geprüft.", deleted: "Schlüssel gelöscht. Die Diktierfunktion ist deaktiviert.", loadError: "Die Integration konnte nicht geladen werden.", saveError: "Der Schlüssel konnte nicht gespeichert werden. Das Feld wurde sicherheitshalber geleert.", testFailed: "ElevenLabs hat den Test abgelehnt oder nicht geantwortet.", deleteError: "Der Schlüssel konnte nicht gelöscht werden.", offline: "Stelle die Verbindung wieder her, um diese Integration zu verwalten.",
  } },
  pt: { integrations: {
    title: "Integrações", description: "Conecte sua própria conta da ElevenLabs para ativar o ditado.", loading: "Verificando…", configured: "Configurado", notConfigured: "Não configurado",
    autoLanguage: "idioma automático", apiKey: "Chave da API ElevenLabs", replaceKey: "Substituir chave da API", keyPlaceholder: "Cole uma chave da API", keyConfiguredPlaceholder: "Configurada · digite para substituir", writeOnlyHint: "A chave é enviada uma vez ao Agent Control para ser criptografada; ela não é salva neste dispositivo nem retorna nas respostas.",
    audioDisclosure: "Ao ditar, o áudio é enviado diretamente à ElevenLabs com um token temporário. A chave da API permanece no backend.", nativeFallback: "Sem configurar a ElevenLabs, você ainda pode usar o ditado nativo do teclado do celular.", save: "Salvar criptografada", replace: "Substituir chave", saving: "Salvando…", test: "Testar conexão", testing: "Testando…", delete: "Excluir chave", deleting: "Excluindo…", cancel: "Cancelar", confirmDelete: "Excluir", deleteConfirm: "Excluir sua chave da ElevenLabs? O ditado deixará de estar disponível.",
    saved: "Chave salva. O ditado já está disponível.", testPassed: "Conexão verificada com sucesso.", deleted: "Chave excluída. O ditado foi desativado.", loadError: "Não foi possível carregar a integração.", saveError: "Não foi possível salvar a chave. O campo foi apagado por segurança.", testFailed: "A ElevenLabs recusou o teste ou não respondeu.", deleteError: "Não foi possível excluir a chave.", offline: "Reconecte-se para gerenciar esta integração.",
  } },
} as const;
