export const integrationResources = {
  es: { integrations: {
    title: "Integraciones", description: "Conecta tu propia cuenta de ElevenLabs para dictar y escuchar las respuestas de tus agentes.", loading: "Consultando…", configured: "Configurado", notConfigured: "Sin configurar",
    autoLanguage: "idioma automático", apiKey: "API key de ElevenLabs", replaceKey: "Reemplazar API key", keyPlaceholder: "Pega una API key", keyConfiguredPlaceholder: "Configurada · escribe para reemplazar", writeOnlyHint: "La clave se envía una vez a Agent Control para cifrarse; no se guarda en este dispositivo ni vuelve en las respuestas.",
    audioDisclosure: "Al dictar, el audio se envía a ElevenLabs; al escuchar, se envía el texto visible de la respuesta. La API key permanece en el backend.", nativeFallback: "Sin configurar ElevenLabs, puedes seguir usando el dictado nativo del teclado de tu móvil.", save: "Guardar cifrada", replace: "Reemplazar clave", saving: "Guardando…", test: "Probar conexión", testing: "Probando…", delete: "Eliminar clave", deleting: "Eliminando…", cancel: "Cancelar", confirmDelete: "Eliminar", deleteConfirm: "¿Eliminar tu clave de ElevenLabs? El dictado y la lectura de respuestas dejarán de estar disponibles.",
    saved: "Clave guardada. El dictado está disponible; elige una voz para escuchar respuestas.", testPassed: "Conexión verificada correctamente.", deleted: "Clave eliminada. El dictado y la lectura quedaron desactivados.", loadError: "No se pudo consultar la integración.", saveError: "No se pudo guardar la clave. El campo se vació por seguridad.", testFailed: "ElevenLabs rechazó la prueba o no respondió.", deleteError: "No se pudo eliminar la clave.", offline: "Reconéctate para administrar esta integración.",
    voice: "Voz para respuestas", voiceHint: "Elige una voz de tu catálogo de ElevenLabs.", loadingVoices: "Cargando voces…", chooseVoice: "Selecciona una voz", previewVoice: "Probar voz", loadingPreview: "Cargando muestra…", pausePreview: "Pausar prueba", resumePreview: "Continuar prueba", previewUnavailable: "Esta voz no incluye una muestra de audio.", previewError: "No se pudo reproducir la muestra de esta voz.", saveVoice: "Usar esta voz", savingVoice: "Guardando…", currentVoice: "Voz activa: {{voice}}", voiceRequired: "Selecciona una voz para activar la lectura de respuestas.", voiceSaved: "{{voice}} ya es la voz para tus agentes.", voicesError: "No se pudo cargar el catálogo de voces.", voiceSaveError: "No se pudo guardar la voz seleccionada.",
  } },
  en: { integrations: {
    title: "Integrations", description: "Connect your own ElevenLabs account to dictate and listen to agent responses.", loading: "Checking…", configured: "Configured", notConfigured: "Not configured",
    autoLanguage: "automatic language", apiKey: "ElevenLabs API key", replaceKey: "Replace API key", keyPlaceholder: "Paste an API key", keyConfiguredPlaceholder: "Configured · type to replace", writeOnlyHint: "The key is sent once to Agent Control for encryption; it is not stored on this device or returned in responses.",
    audioDisclosure: "When dictating, audio is sent to ElevenLabs; when listening, visible response text is sent. The API key remains in the backend.", nativeFallback: "Without configuring ElevenLabs, you can still use your mobile keyboard’s built-in dictation.", save: "Save encrypted", replace: "Replace key", saving: "Saving…", test: "Test connection", testing: "Testing…", delete: "Delete key", deleting: "Deleting…", cancel: "Cancel", confirmDelete: "Delete", deleteConfirm: "Delete your ElevenLabs key? Dictation and response playback will no longer be available.",
    saved: "Key saved. Dictation is available; choose a voice to hear responses.", testPassed: "Connection verified successfully.", deleted: "Key deleted. Dictation and response playback are now disabled.", loadError: "The integration could not be loaded.", saveError: "The key could not be saved. The field was cleared for safety.", testFailed: "ElevenLabs rejected the test or did not respond.", deleteError: "The key could not be deleted.", offline: "Reconnect to manage this integration.",
    voice: "Response voice", voiceHint: "Choose a voice from your ElevenLabs catalog.", loadingVoices: "Loading voices…", chooseVoice: "Choose a voice", previewVoice: "Try voice", loadingPreview: "Loading sample…", pausePreview: "Pause preview", resumePreview: "Resume preview", previewUnavailable: "This voice does not include an audio sample.", previewError: "This voice sample could not be played.", saveVoice: "Use this voice", savingVoice: "Saving…", currentVoice: "Active voice: {{voice}}", voiceRequired: "Choose a voice to enable response playback.", voiceSaved: "{{voice}} is now your agents’ voice.", voicesError: "The voice catalog could not be loaded.", voiceSaveError: "The selected voice could not be saved.",
  } },
  fr: { integrations: {
    title: "Intégrations", description: "Connectez votre compte ElevenLabs pour dicter et écouter les réponses des agents.", loading: "Vérification…", configured: "Configuré", notConfigured: "Non configuré",
    autoLanguage: "langue automatique", apiKey: "Clé API ElevenLabs", replaceKey: "Remplacer la clé API", keyPlaceholder: "Collez une clé API", keyConfiguredPlaceholder: "Configurée · saisissez pour remplacer", writeOnlyHint: "La clé est envoyée une seule fois à Agent Control pour être chiffrée ; elle n’est ni stockée sur cet appareil ni renvoyée dans les réponses.",
    audioDisclosure: "Pendant la dictée, l’audio est envoyé à ElevenLabs ; pendant l’écoute, le texte visible de la réponse est envoyé. La clé API reste dans le backend.", nativeFallback: "Sans configurer ElevenLabs, vous pouvez continuer à utiliser la dictée intégrée au clavier de votre mobile.", save: "Enregistrer chiffrée", replace: "Remplacer la clé", saving: "Enregistrement…", test: "Tester la connexion", testing: "Test…", delete: "Supprimer la clé", deleting: "Suppression…", cancel: "Annuler", confirmDelete: "Supprimer", deleteConfirm: "Supprimer votre clé ElevenLabs ? La dictée et la lecture des réponses ne seront plus disponibles.",
    saved: "Clé enregistrée. La dictée est disponible ; choisissez une voix pour écouter les réponses.", testPassed: "Connexion vérifiée avec succès.", deleted: "Clé supprimée. La dictée et la lecture sont désactivées.", loadError: "Impossible de charger l’intégration.", saveError: "Impossible d’enregistrer la clé. Le champ a été effacé par sécurité.", testFailed: "ElevenLabs a refusé le test ou n’a pas répondu.", deleteError: "Impossible de supprimer la clé.", offline: "Reconnectez-vous pour gérer cette intégration.",
    voice: "Voix des réponses", voiceHint: "Choisissez une voix dans votre catalogue ElevenLabs.", loadingVoices: "Chargement des voix…", chooseVoice: "Choisir une voix", previewVoice: "Tester la voix", loadingPreview: "Chargement de l’extrait…", pausePreview: "Mettre en pause", resumePreview: "Reprendre l’extrait", previewUnavailable: "Cette voix ne contient pas d’extrait audio.", previewError: "Impossible de lire l’extrait de cette voix.", saveVoice: "Utiliser cette voix", savingVoice: "Enregistrement…", currentVoice: "Voix active : {{voice}}", voiceRequired: "Choisissez une voix pour activer la lecture des réponses.", voiceSaved: "{{voice}} est maintenant la voix de vos agents.", voicesError: "Impossible de charger le catalogue de voix.", voiceSaveError: "Impossible d’enregistrer la voix sélectionnée.",
  } },
  de: { integrations: {
    title: "Integrationen", description: "Verbinde dein ElevenLabs-Konto, um zu diktieren und Agentenantworten anzuhören.", loading: "Wird geprüft…", configured: "Konfiguriert", notConfigured: "Nicht konfiguriert",
    autoLanguage: "automatische Sprache", apiKey: "ElevenLabs-API-Schlüssel", replaceKey: "API-Schlüssel ersetzen", keyPlaceholder: "API-Schlüssel einfügen", keyConfiguredPlaceholder: "Konfiguriert · zum Ersetzen eingeben", writeOnlyHint: "Der Schlüssel wird einmalig zur Verschlüsselung an Agent Control gesendet; er wird weder auf diesem Gerät gespeichert noch in Antworten zurückgegeben.",
    audioDisclosure: "Beim Diktieren wird Audio an ElevenLabs gesendet; beim Anhören wird der sichtbare Antworttext gesendet. Der API-Schlüssel bleibt im Backend.", nativeFallback: "Ohne ElevenLabs einzurichten, kannst du weiterhin die integrierte Diktierfunktion deiner mobilen Tastatur verwenden.", save: "Verschlüsselt speichern", replace: "Schlüssel ersetzen", saving: "Wird gespeichert…", test: "Verbindung testen", testing: "Wird getestet…", delete: "Schlüssel löschen", deleting: "Wird gelöscht…", cancel: "Abbrechen", confirmDelete: "Löschen", deleteConfirm: "Deinen ElevenLabs-Schlüssel löschen? Diktat und Antwortwiedergabe sind danach nicht mehr verfügbar.",
    saved: "Schlüssel gespeichert. Diktat ist verfügbar; wähle eine Stimme für Antworten.", testPassed: "Verbindung erfolgreich geprüft.", deleted: "Schlüssel gelöscht. Diktat und Antwortwiedergabe sind deaktiviert.", loadError: "Die Integration konnte nicht geladen werden.", saveError: "Der Schlüssel konnte nicht gespeichert werden. Das Feld wurde sicherheitshalber geleert.", testFailed: "ElevenLabs hat den Test abgelehnt oder nicht geantwortet.", deleteError: "Der Schlüssel konnte nicht gelöscht werden.", offline: "Stelle die Verbindung wieder her, um diese Integration zu verwalten.",
    voice: "Stimme für Antworten", voiceHint: "Wähle eine Stimme aus deinem ElevenLabs-Katalog.", loadingVoices: "Stimmen werden geladen…", chooseVoice: "Stimme auswählen", previewVoice: "Stimme testen", loadingPreview: "Hörprobe wird geladen…", pausePreview: "Hörprobe pausieren", resumePreview: "Hörprobe fortsetzen", previewUnavailable: "Für diese Stimme ist keine Hörprobe verfügbar.", previewError: "Die Hörprobe konnte nicht abgespielt werden.", saveVoice: "Diese Stimme verwenden", savingVoice: "Wird gespeichert…", currentVoice: "Aktive Stimme: {{voice}}", voiceRequired: "Wähle eine Stimme, um Antworten vorlesen zu lassen.", voiceSaved: "{{voice}} ist jetzt die Stimme deiner Agenten.", voicesError: "Der Stimmenkatalog konnte nicht geladen werden.", voiceSaveError: "Die ausgewählte Stimme konnte nicht gespeichert werden.",
  } },
  pt: { integrations: {
    title: "Integrações", description: "Conecte sua conta da ElevenLabs para ditar e ouvir as respostas dos agentes.", loading: "Verificando…", configured: "Configurado", notConfigured: "Não configurado",
    autoLanguage: "idioma automático", apiKey: "Chave da API ElevenLabs", replaceKey: "Substituir chave da API", keyPlaceholder: "Cole uma chave da API", keyConfiguredPlaceholder: "Configurada · digite para substituir", writeOnlyHint: "A chave é enviada uma vez ao Agent Control para ser criptografada; ela não é salva neste dispositivo nem retorna nas respostas.",
    audioDisclosure: "Ao ditar, o áudio é enviado à ElevenLabs; ao ouvir, o texto visível da resposta é enviado. A chave da API permanece no backend.", nativeFallback: "Sem configurar a ElevenLabs, você ainda pode usar o ditado nativo do teclado do celular.", save: "Salvar criptografada", replace: "Substituir chave", saving: "Salvando…", test: "Testar conexão", testing: "Testando…", delete: "Excluir chave", deleting: "Excluindo…", cancel: "Cancelar", confirmDelete: "Excluir", deleteConfirm: "Excluir sua chave da ElevenLabs? O ditado e a reprodução de respostas deixarão de estar disponíveis.",
    saved: "Chave salva. O ditado está disponível; escolha uma voz para ouvir respostas.", testPassed: "Conexão verificada com sucesso.", deleted: "Chave excluída. O ditado e a reprodução foram desativados.", loadError: "Não foi possível carregar a integração.", saveError: "Não foi possível salvar a chave. O campo foi apagado por segurança.", testFailed: "A ElevenLabs recusou o teste ou não respondeu.", deleteError: "Não foi possível excluir a chave.", offline: "Reconecte-se para gerenciar esta integração.",
    voice: "Voz das respostas", voiceHint: "Escolha uma voz do seu catálogo da ElevenLabs.", loadingVoices: "Carregando vozes…", chooseVoice: "Escolha uma voz", previewVoice: "Testar voz", loadingPreview: "Carregando amostra…", pausePreview: "Pausar amostra", resumePreview: "Continuar amostra", previewUnavailable: "Esta voz não inclui uma amostra de áudio.", previewError: "Não foi possível reproduzir a amostra desta voz.", saveVoice: "Usar esta voz", savingVoice: "Salvando…", currentVoice: "Voz ativa: {{voice}}", voiceRequired: "Escolha uma voz para ativar a leitura das respostas.", voiceSaved: "{{voice}} agora é a voz dos seus agentes.", voicesError: "Não foi possível carregar o catálogo de vozes.", voiceSaveError: "Não foi possível salvar a voz selecionada.",
  } },
} as const;
