export const liveVoiceResources = {
  es: {
    voiceSettings: {
      scope: "Configurar voz de", generalVoice: "Voz general", scopeHint: "Cada agente puede tener su propia voz. Si no eliges una, usará la general.", useGeneral: "Usar voz general", inheritedVoice: "Usa la voz general: {{voice}}", agentVoice: "Voz de este agente: {{voice}}",
      voice: "Voz de GPT-Live-1", voiceHint: "La voz elegida se usará al iniciar la próxima conversación.", saveVoice: "Guardar voz", savingVoice: "Guardando voz…", voiceSaved: "Voz guardada para la próxima conversación.", voiceSaveError: "No se pudo guardar la voz. Tu voz guardada no cambió.", voiceLoadError: "No se pudo cargar la voz guardada.", currentVoice: "Voz guardada: {{voice}}", preview: "Probar voz", stopPreview: "Detener muestra", loadingPreview: "Generando muestra…", playPreview: "Reproducir muestra", previewHint: "Genera una muestra breve con GPT-Live-1 en el idioma de la interfaz. Cada prueba usa tu API de OpenAI y factura al menos 15 segundos; no activa el micrófono.", previewKeyRequired: "Guarda una API key de OpenAI para probar las voces.", previewUnavailable: "Este navegador no permite generar muestras de voz.", previewError: "No se pudo reproducir la muestra. Inténtalo de nuevo.",
      title: "Modo de voz", description: "Elige cómo conversar por voz con tus agentes.", mode: "Proveedor de voz", elevenLabs: "ElevenLabs · dictado y lectura", elevenLabsHint: "Dicta un borrador, revísalo y envíalo. Las respuestas se leen con tu voz de ElevenLabs.", liveHint: "Conversación de voz en tiempo real. GPT-Live-1 puede responder y enviar solicitudes al agente seleccionado.", keyRequired: "Guarda una API key de OpenAI para habilitar GPT-Live-1.",
      apiKey: "API key de OpenAI", replaceKey: "Reemplazar API key de OpenAI", disclosure: "En una conversación en vivo, el micrófono y el contexto compartido se envían a OpenAI. GPT-Live-1 puede enviar tus solicitudes automáticamente al agente seleccionado; las aprobaciones del agente siguen vigentes.",
      modeSaved: "Modo de voz guardado.", modeError: "No se pudo cambiar el modo de voz.", loadError: "No se pudo cargar la configuración de voz.", saved: "Clave guardada cifrada. Ya puedes seleccionar GPT-Live-1; el acceso al modelo se comprobará al iniciar una conversación.", saveError: "No se pudo guardar la clave de OpenAI. El campo se vació por seguridad.", deleted: "Clave de OpenAI eliminada. Se seleccionó el modo ElevenLabs.", deleteError: "No se pudo eliminar la clave de OpenAI.", deleteConfirm: "¿Eliminar tu clave de OpenAI? GPT-Live-1 dejará de estar disponible y se seleccionará el modo ElevenLabs.",
    },
    liveVoice: {
      start: "Conversar con GPT-Live-1", stop: "Terminar conversación de voz", connecting: "Conectando con GPT-Live-1…", listening: "Conversación en vivo", stopping: "Terminando conversación…", disclosure: "El audio y el contexto se envían a OpenAI. GPT-Live-1 puede enviar solicitudes automáticamente al agente seleccionado.", inputCaption: "Tú", outputCaption: "GPT-Live-1", working: "El agente está trabajando…", playAudio: "Activar audio", unavailable: "La conversación en vivo no está disponible en este navegador.", permissionDenied: "No se concedió acceso al micrófono. Habilítalo en los permisos del navegador.", auth: "No se pudo autorizar GPT-Live-1. Revisa tu clave de OpenAI y el acceso al modelo en Configuración.", quota: "OpenAI no tiene cuota disponible o limitó la solicitud.", network: "Se perdió la conexión de voz. Vuelve a iniciar la conversación.", generic: "No se pudo iniciar la conversación de voz.", unconfirmed: "No se pudo confirmar el último audio. Repítelo al reconectar.", agentFailed: "No se pudo enviar la solicitud al agente. Inténtalo de nuevo.", waitingApproval: "El agente necesita tu aprobación en el chat.", contextFull: "La conversación alcanzó su límite de contexto. Inicia una nueva conversación de voz.",
    },
  },
  en: {
    voiceSettings: {
      scope: "Configure voice for", generalVoice: "Default voice", scopeHint: "Each agent can have its own voice. Agents without a custom choice use the default.", useGeneral: "Use default voice", inheritedVoice: "Uses the default voice: {{voice}}", agentVoice: "This agent’s voice: {{voice}}",
      voice: "GPT-Live-1 voice", voiceHint: "The selected voice will apply when your next conversation starts.", saveVoice: "Save voice", savingVoice: "Saving voice…", voiceSaved: "Voice saved for the next conversation.", voiceSaveError: "The voice could not be saved. Your saved voice has not changed.", voiceLoadError: "The saved voice could not be loaded.", currentVoice: "Saved voice: {{voice}}", preview: "Try voice", stopPreview: "Stop sample", loadingPreview: "Generating sample…", playPreview: "Play sample", previewHint: "Generate a short GPT-Live-1 sample in the interface language. Each test uses your OpenAI API and bills at least 15 seconds; it does not activate the microphone.", previewKeyRequired: "Save an OpenAI API key to try the voices.", previewUnavailable: "This browser cannot generate voice samples.", previewError: "The sample could not be played. Try again.",
      title: "Voice mode", description: "Choose how to talk with your agents.", mode: "Voice provider", elevenLabs: "ElevenLabs · dictation and playback", elevenLabsHint: "Dictate a draft, review it, and send it. Responses use your ElevenLabs voice.", liveHint: "Real-time voice conversation. GPT-Live-1 can respond and send requests to the selected agent.", keyRequired: "Save an OpenAI API key to enable GPT-Live-1.",
      apiKey: "OpenAI API key", replaceKey: "Replace OpenAI API key", disclosure: "During a live conversation, microphone audio and shared context are sent to OpenAI. GPT-Live-1 can send your requests automatically to the selected agent; agent approvals still apply.",
      modeSaved: "Voice mode saved.", modeError: "The voice mode could not be changed.", loadError: "Voice settings could not be loaded.", saved: "Key saved encrypted. You can now select GPT-Live-1; model access will be checked when a conversation starts.", saveError: "The OpenAI key could not be saved. The field was cleared for safety.", deleted: "OpenAI key deleted. ElevenLabs mode is selected.", deleteError: "The OpenAI key could not be deleted.", deleteConfirm: "Delete your OpenAI key? GPT-Live-1 will become unavailable and ElevenLabs mode will be selected.",
    },
    liveVoice: {
      start: "Talk with GPT-Live-1", stop: "End voice conversation", connecting: "Connecting to GPT-Live-1…", listening: "Live conversation", stopping: "Ending conversation…", disclosure: "Audio and context are sent to OpenAI. GPT-Live-1 can send requests automatically to the selected agent.", inputCaption: "You", outputCaption: "GPT-Live-1", working: "The agent is working…", playAudio: "Enable audio", unavailable: "Live conversation is not available in this browser.", permissionDenied: "Microphone access was not granted. Enable it in your browser permissions.", auth: "GPT-Live-1 could not be authorized. Check your OpenAI key and model access in Settings.", quota: "OpenAI has no available quota or rate-limited the request.", network: "The voice connection was lost. Start the conversation again.", generic: "The voice conversation could not be started.", unconfirmed: "The last audio could not be confirmed. Repeat it after reconnecting.", agentFailed: "The request could not be sent to the agent. Try again.", waitingApproval: "The agent needs your approval in the chat.", contextFull: "This conversation reached its context limit. Start a new voice conversation.",
    },
  },
  fr: {
    voiceSettings: {
      scope: "Configurer la voix de", generalVoice: "Voix générale", scopeHint: "Chaque agent peut avoir sa propre voix. Sans choix spécifique, il utilise la voix générale.", useGeneral: "Utiliser la voix générale", inheritedVoice: "Utilise la voix générale : {{voice}}", agentVoice: "Voix de cet agent : {{voice}}",
      voice: "Voix de GPT-Live-1", voiceHint: "La voix choisie sera utilisée au début de la prochaine conversation.", saveVoice: "Enregistrer la voix", savingVoice: "Enregistrement…", voiceSaved: "Voix enregistrée pour la prochaine conversation.", voiceSaveError: "Impossible d’enregistrer la voix. Votre voix enregistrée n’a pas changé.", voiceLoadError: "Impossible de charger la voix enregistrée.", currentVoice: "Voix enregistrée : {{voice}}", preview: "Essayer la voix", stopPreview: "Arrêter l’extrait", loadingPreview: "Génération de l’extrait…", playPreview: "Lire l’extrait", previewHint: "Générez un bref extrait GPT-Live-1 dans la langue de l’interface. Chaque essai utilise votre API OpenAI et facture au moins 15 secondes ; le microphone reste désactivé.", previewKeyRequired: "Enregistrez une clé API OpenAI pour essayer les voix.", previewUnavailable: "Ce navigateur ne permet pas de générer des extraits vocaux.", previewError: "Impossible de lire l’extrait. Réessayez.",
      title: "Mode vocal", description: "Choisissez comment parler avec vos agents.", mode: "Fournisseur vocal", elevenLabs: "ElevenLabs · dictée et lecture", elevenLabsHint: "Dictez un brouillon, vérifiez-le et envoyez-le. Les réponses utilisent votre voix ElevenLabs.", liveHint: "Conversation vocale en temps réel. GPT-Live-1 peut répondre et envoyer des demandes à l’agent sélectionné.", keyRequired: "Enregistrez une clé API OpenAI pour activer GPT-Live-1.",
      apiKey: "Clé API OpenAI", replaceKey: "Remplacer la clé API OpenAI", disclosure: "Pendant une conversation en direct, l’audio du microphone et le contexte partagé sont envoyés à OpenAI. GPT-Live-1 peut transmettre automatiquement vos demandes à l’agent sélectionné ; les approbations de l’agent restent nécessaires.",
      modeSaved: "Mode vocal enregistré.", modeError: "Impossible de changer le mode vocal.", loadError: "Impossible de charger les paramètres vocaux.", saved: "Clé enregistrée chiffrée. Vous pouvez sélectionner GPT-Live-1 ; l’accès au modèle sera vérifié au début d’une conversation.", saveError: "Impossible d’enregistrer la clé OpenAI. Le champ a été effacé par sécurité.", deleted: "Clé OpenAI supprimée. Le mode ElevenLabs est sélectionné.", deleteError: "Impossible de supprimer la clé OpenAI.", deleteConfirm: "Supprimer votre clé OpenAI ? GPT-Live-1 deviendra indisponible et le mode ElevenLabs sera sélectionné.",
    },
    liveVoice: {
      start: "Parler avec GPT-Live-1", stop: "Terminer la conversation vocale", connecting: "Connexion à GPT-Live-1…", listening: "Conversation en direct", stopping: "Fin de la conversation…", disclosure: "L’audio et le contexte sont envoyés à OpenAI. GPT-Live-1 peut transmettre automatiquement des demandes à l’agent sélectionné.", inputCaption: "Vous", outputCaption: "GPT-Live-1", working: "L’agent travaille…", playAudio: "Activer l’audio", unavailable: "La conversation en direct n’est pas disponible dans ce navigateur.", permissionDenied: "L’accès au microphone a été refusé. Autorisez-le dans les permissions du navigateur.", auth: "Impossible d’autoriser GPT-Live-1. Vérifiez votre clé OpenAI et l’accès au modèle dans les paramètres.", quota: "OpenAI n’a plus de quota disponible ou a limité la requête.", network: "La connexion vocale a été perdue. Relancez la conversation.", generic: "Impossible de démarrer la conversation vocale.", unconfirmed: "Le dernier audio n’a pas pu être confirmé. Répétez-le après la reconnexion.", agentFailed: "Impossible d’envoyer la demande à l’agent. Réessayez.", waitingApproval: "L’agent attend votre approbation dans la conversation.", contextFull: "Cette conversation a atteint sa limite de contexte. Démarrez une nouvelle conversation vocale.",
    },
  },
  de: {
    voiceSettings: {
      scope: "Stimme einstellen für", generalVoice: "Standardstimme", scopeHint: "Jeder Agent kann eine eigene Stimme haben. Ohne eigene Auswahl verwendet er die Standardstimme.", useGeneral: "Standardstimme verwenden", inheritedVoice: "Verwendet die Standardstimme: {{voice}}", agentVoice: "Stimme dieses Agenten: {{voice}}",
      voice: "GPT-Live-1-Stimme", voiceHint: "Die gewählte Stimme wird beim nächsten Gespräch verwendet.", saveVoice: "Stimme speichern", savingVoice: "Stimme wird gespeichert…", voiceSaved: "Stimme für das nächste Gespräch gespeichert.", voiceSaveError: "Die Stimme konnte nicht gespeichert werden. Deine gespeicherte Stimme wurde nicht geändert.", voiceLoadError: "Die gespeicherte Stimme konnte nicht geladen werden.", currentVoice: "Gespeicherte Stimme: {{voice}}", preview: "Stimme testen", stopPreview: "Hörprobe stoppen", loadingPreview: "Hörprobe wird erzeugt…", playPreview: "Hörprobe abspielen", previewHint: "Erzeuge eine kurze GPT-Live-1-Hörprobe in der Sprache der Oberfläche. Jeder Test verwendet deine OpenAI-API und berechnet mindestens 15 Sekunden; das Mikrofon wird nicht aktiviert.", previewKeyRequired: "Speichere einen OpenAI-API-Schlüssel, um die Stimmen zu testen.", previewUnavailable: "Dieser Browser kann keine Hörproben erzeugen.", previewError: "Die Hörprobe konnte nicht abgespielt werden. Versuche es erneut.",
      title: "Sprachmodus", description: "Wähle, wie du mit deinen Agenten sprichst.", mode: "Sprachanbieter", elevenLabs: "ElevenLabs · Diktat und Wiedergabe", elevenLabsHint: "Diktiere einen Entwurf, prüfe ihn und sende ihn. Antworten verwenden deine ElevenLabs-Stimme.", liveHint: "Sprachgespräch in Echtzeit. GPT-Live-1 kann antworten und Anfragen an den ausgewählten Agenten senden.", keyRequired: "Speichere einen OpenAI-API-Schlüssel, um GPT-Live-1 zu aktivieren.",
      apiKey: "OpenAI-API-Schlüssel", replaceKey: "OpenAI-API-Schlüssel ersetzen", disclosure: "Während eines Live-Gesprächs werden Mikrofon-Audio und geteilter Kontext an OpenAI gesendet. GPT-Live-1 kann deine Anfragen automatisch an den ausgewählten Agenten senden; dessen Freigaben gelten weiterhin.",
      modeSaved: "Sprachmodus gespeichert.", modeError: "Der Sprachmodus konnte nicht geändert werden.", loadError: "Die Spracheinstellungen konnten nicht geladen werden.", saved: "Schlüssel verschlüsselt gespeichert. Du kannst jetzt GPT-Live-1 auswählen; der Modellzugriff wird beim Start eines Gesprächs geprüft.", saveError: "Der OpenAI-Schlüssel konnte nicht gespeichert werden. Das Feld wurde sicherheitshalber geleert.", deleted: "OpenAI-Schlüssel gelöscht. Der ElevenLabs-Modus ist ausgewählt.", deleteError: "Der OpenAI-Schlüssel konnte nicht gelöscht werden.", deleteConfirm: "Deinen OpenAI-Schlüssel löschen? GPT-Live-1 ist dann nicht mehr verfügbar und der ElevenLabs-Modus wird ausgewählt.",
    },
    liveVoice: {
      start: "Mit GPT-Live-1 sprechen", stop: "Sprachgespräch beenden", connecting: "Verbindung mit GPT-Live-1…", listening: "Live-Gespräch", stopping: "Gespräch wird beendet…", disclosure: "Audio und Kontext werden an OpenAI gesendet. GPT-Live-1 kann Anfragen automatisch an den ausgewählten Agenten senden.", inputCaption: "Du", outputCaption: "GPT-Live-1", working: "Der Agent arbeitet…", playAudio: "Audio aktivieren", unavailable: "Live-Gespräche sind in diesem Browser nicht verfügbar.", permissionDenied: "Der Mikrofonzugriff wurde nicht erteilt. Aktiviere ihn in den Browserberechtigungen.", auth: "GPT-Live-1 konnte nicht autorisiert werden. Prüfe deinen OpenAI-Schlüssel und den Modellzugriff in den Einstellungen.", quota: "OpenAI hat kein verfügbares Kontingent oder hat die Anfrage begrenzt.", network: "Die Sprachverbindung wurde unterbrochen. Starte das Gespräch erneut.", generic: "Das Sprachgespräch konnte nicht gestartet werden.", unconfirmed: "Die letzte Audioeingabe konnte nicht bestätigt werden. Wiederhole sie nach dem erneuten Verbinden.", agentFailed: "Die Anfrage konnte nicht an den Agenten gesendet werden. Versuche es erneut.", waitingApproval: "Der Agent benötigt deine Freigabe im Chat.", contextFull: "Dieses Gespräch hat sein Kontextlimit erreicht. Starte ein neues Sprachgespräch.",
    },
  },
  pt: {
    voiceSettings: {
      scope: "Configurar voz de", generalVoice: "Voz geral", scopeHint: "Cada agente pode ter sua própria voz. Sem uma escolha específica, ele usa a voz geral.", useGeneral: "Usar voz geral", inheritedVoice: "Usa a voz geral: {{voice}}", agentVoice: "Voz deste agente: {{voice}}",
      voice: "Voz do GPT-Live-1", voiceHint: "A voz escolhida será usada ao iniciar a próxima conversa.", saveVoice: "Salvar voz", savingVoice: "Salvando voz…", voiceSaved: "Voz salva para a próxima conversa.", voiceSaveError: "Não foi possível salvar a voz. Sua voz salva não foi alterada.", voiceLoadError: "Não foi possível carregar a voz salva.", currentVoice: "Voz salva: {{voice}}", preview: "Testar voz", stopPreview: "Parar amostra", loadingPreview: "Gerando amostra…", playPreview: "Reproduzir amostra", previewHint: "Gere uma amostra breve do GPT-Live-1 no idioma da interface. Cada teste usa sua API OpenAI e cobra pelo menos 15 segundos; o microfone não é ativado.", previewKeyRequired: "Salve uma chave da API OpenAI para testar as vozes.", previewUnavailable: "Este navegador não permite gerar amostras de voz.", previewError: "Não foi possível reproduzir a amostra. Tente novamente.",
      title: "Modo de voz", description: "Escolha como conversar por voz com seus agentes.", mode: "Provedor de voz", elevenLabs: "ElevenLabs · ditado e reprodução", elevenLabsHint: "Dite um rascunho, revise e envie. As respostas usam sua voz da ElevenLabs.", liveHint: "Conversa por voz em tempo real. O GPT-Live-1 pode responder e enviar solicitações ao agente selecionado.", keyRequired: "Salve uma chave da API OpenAI para ativar o GPT-Live-1.",
      apiKey: "Chave da API OpenAI", replaceKey: "Substituir chave da API OpenAI", disclosure: "Durante uma conversa ao vivo, o áudio do microfone e o contexto compartilhado são enviados à OpenAI. O GPT-Live-1 pode enviar suas solicitações automaticamente ao agente selecionado; as aprovações do agente continuam valendo.",
      modeSaved: "Modo de voz salvo.", modeError: "Não foi possível alterar o modo de voz.", loadError: "Não foi possível carregar as configurações de voz.", saved: "Chave salva criptografada. Você já pode selecionar o GPT-Live-1; o acesso ao modelo será verificado ao iniciar uma conversa.", saveError: "Não foi possível salvar a chave da OpenAI. O campo foi apagado por segurança.", deleted: "Chave da OpenAI excluída. O modo ElevenLabs está selecionado.", deleteError: "Não foi possível excluir a chave da OpenAI.", deleteConfirm: "Excluir sua chave da OpenAI? O GPT-Live-1 ficará indisponível e o modo ElevenLabs será selecionado.",
    },
    liveVoice: {
      start: "Conversar com GPT-Live-1", stop: "Encerrar conversa por voz", connecting: "Conectando ao GPT-Live-1…", listening: "Conversa ao vivo", stopping: "Encerrando conversa…", disclosure: "O áudio e o contexto são enviados à OpenAI. O GPT-Live-1 pode enviar solicitações automaticamente ao agente selecionado.", inputCaption: "Você", outputCaption: "GPT-Live-1", working: "O agente está trabalhando…", playAudio: "Ativar áudio", unavailable: "A conversa ao vivo não está disponível neste navegador.", permissionDenied: "O acesso ao microfone não foi concedido. Ative-o nas permissões do navegador.", auth: "Não foi possível autorizar o GPT-Live-1. Verifique sua chave da OpenAI e o acesso ao modelo nas configurações.", quota: "A OpenAI não tem cota disponível ou limitou a solicitação.", network: "A conexão de voz foi perdida. Inicie a conversa novamente.", generic: "Não foi possível iniciar a conversa por voz.", unconfirmed: "Não foi possível confirmar o último áudio. Repita após reconectar.", agentFailed: "Não foi possível enviar a solicitação ao agente. Tente novamente.", waitingApproval: "O agente precisa da sua aprovação no chat.", contextFull: "Esta conversa atingiu o limite de contexto. Inicie uma nova conversa por voz.",
    },
  },
} as const;
