export const runtimeResources = {
  es: { runtimeMessages: {
    demoResponse: "Puedo continuar con el análisis dentro de esta sesión sin mezclar el contexto de otros perfiles. Como siguiente paso, contrastaré los resultados con las capacidades detectadas y dejaré una recomendación verificable.",
    operationFailed: "Hermes confirmó que la operación terminó con error.", acceptedFailed: "El agente aceptó el mensaje, pero la ejecución terminó con error. Revisa la configuración del perfil e inténtalo de nuevo.", interrupted: "La ejecución fue interrumpida.",
    ambiguousPrompt: "La conexión se interrumpió antes de confirmar la operación. No reenviaré el mensaje automáticamente.", rejectedPrompt: "Agent Control rechazó el envío antes de aceptarlo. Puedes revisar la conexión e intentarlo de nuevo manualmente.",
    deliveryUnknown: "El resultado no está confirmado. Los controles permanecerán bloqueados hasta que Hermes reconcilie la solicitud.", noLongerPending: "Hermes no confirmó que la solicitud siga pendiente.", rejectedResponse: "Agent Control rechazó la respuesta.", responseFailed: "No se pudo confirmar la respuesta. Revisa la conexión e inténtalo de nuevo.",
    stopUnknown: "No se pudo confirmar la detención; la ejecución podría continuar en Hermes.", stopped: "Ejecución detenida.",
  }, searchMeta: { agent: "Agente", history: "historial", conversation: "Conversación de Hermes", sessionCount: "{{count}} sesiones", workspace: "Workspace · {{count}} sesiones", activeAutomation: "Automatización activa", pausedAutomation: "Automatización pausada" } },
  en: { runtimeMessages: {
    demoResponse: "I can continue the analysis within this session without mixing context from other profiles. Next, I will compare the results with the detected capabilities and provide a verifiable recommendation.",
    operationFailed: "Hermes confirmed that the operation ended with an error.", acceptedFailed: "The agent accepted the message, but the run ended with an error. Review the profile configuration and try again.", interrupted: "The run was interrupted.",
    ambiguousPrompt: "The connection was interrupted before the operation could be confirmed. I will not resend the message automatically.", rejectedPrompt: "Agent Control rejected the message before accepting it. Review the connection and try again manually.",
    deliveryUnknown: "The result is unconfirmed. Controls will remain locked until Hermes reconciles the request.", noLongerPending: "Hermes did not confirm that the request is still pending.", rejectedResponse: "Agent Control rejected the response.", responseFailed: "The response could not be confirmed. Check the connection and try again.",
    stopUnknown: "The stop could not be confirmed; the run may continue in Hermes.", stopped: "Run stopped.",
  }, searchMeta: { agent: "Agent", history: "history", conversation: "Hermes conversation", sessionCount: "{{count}} sessions", workspace: "Workspace · {{count}} sessions", activeAutomation: "Active automation", pausedAutomation: "Paused automation" } },
  fr: { runtimeMessages: {
    demoResponse: "Je peux poursuivre l’analyse dans cette session sans mélanger le contexte d’autres profils. Je comparerai ensuite les résultats aux capacités détectées et fournirai une recommandation vérifiable.",
    operationFailed: "Hermes a confirmé que l’opération s’est terminée par une erreur.", acceptedFailed: "L’agent a accepté le message, mais l’exécution s’est terminée par une erreur. Vérifiez la configuration du profil et réessayez.", interrupted: "L’exécution a été interrompue.",
    ambiguousPrompt: "La connexion a été interrompue avant la confirmation de l’opération. Le message ne sera pas renvoyé automatiquement.", rejectedPrompt: "Agent Control a rejeté le message avant de l’accepter. Vérifiez la connexion et réessayez manuellement.",
    deliveryUnknown: "Le résultat n’est pas confirmé. Les commandes resteront verrouillées jusqu’à ce que Hermes réconcilie la demande.", noLongerPending: "Hermes n’a pas confirmé que la demande est toujours en attente.", rejectedResponse: "Agent Control a rejeté la réponse.", responseFailed: "La réponse n’a pas pu être confirmée. Vérifiez la connexion et réessayez.",
    stopUnknown: "L’arrêt n’a pas pu être confirmé ; l’exécution peut continuer dans Hermes.", stopped: "Exécution arrêtée.",
  }, searchMeta: { agent: "Agent", history: "historique", conversation: "Conversation Hermes", sessionCount: "{{count}} sessions", workspace: "Workspace · {{count}} sessions", activeAutomation: "Automatisation active", pausedAutomation: "Automatisation en pause" } },
  de: { runtimeMessages: {
    demoResponse: "Ich kann die Analyse in dieser Sitzung fortsetzen, ohne den Kontext anderer Profile zu vermischen. Als Nächstes vergleiche ich die Ergebnisse mit den erkannten Fähigkeiten und liefere eine überprüfbare Empfehlung.",
    operationFailed: "Hermes hat bestätigt, dass der Vorgang mit einem Fehler beendet wurde.", acceptedFailed: "Der Agent hat die Nachricht angenommen, aber die Ausführung endete mit einem Fehler. Prüfen Sie die Profilkonfiguration und versuchen Sie es erneut.", interrupted: "Die Ausführung wurde unterbrochen.",
    ambiguousPrompt: "Die Verbindung wurde unterbrochen, bevor der Vorgang bestätigt werden konnte. Die Nachricht wird nicht automatisch erneut gesendet.", rejectedPrompt: "Agent Control hat die Nachricht vor der Annahme abgelehnt. Prüfen Sie die Verbindung und versuchen Sie es manuell erneut.",
    deliveryUnknown: "Das Ergebnis ist unbestätigt. Die Bedienelemente bleiben gesperrt, bis Hermes die Anfrage abgeglichen hat.", noLongerPending: "Hermes hat nicht bestätigt, dass die Anfrage noch aussteht.", rejectedResponse: "Agent Control hat die Antwort abgelehnt.", responseFailed: "Die Antwort konnte nicht bestätigt werden. Prüfen Sie die Verbindung und versuchen Sie es erneut.",
    stopUnknown: "Das Anhalten konnte nicht bestätigt werden; die Ausführung kann in Hermes fortgesetzt werden.", stopped: "Ausführung angehalten.",
  }, searchMeta: { agent: "Agent", history: "Verlauf", conversation: "Hermes-Unterhaltung", sessionCount: "{{count}} Sitzungen", workspace: "Workspace · {{count}} Sitzungen", activeAutomation: "Aktive Automatisierung", pausedAutomation: "Pausierte Automatisierung" } },
  pt: { runtimeMessages: {
    demoResponse: "Posso continuar a análise nesta sessão sem misturar o contexto de outros perfis. Em seguida, vou comparar os resultados com as capacidades detectadas e fornecer uma recomendação verificável.",
    operationFailed: "O Hermes confirmou que a operação terminou com erro.", acceptedFailed: "O agente aceitou a mensagem, mas a execução terminou com erro. Revise a configuração do perfil e tente novamente.", interrupted: "A execução foi interrompida.",
    ambiguousPrompt: "A conexão foi interrompida antes da confirmação da operação. A mensagem não será reenviada automaticamente.", rejectedPrompt: "O Agent Control rejeitou a mensagem antes de aceitá-la. Revise a conexão e tente novamente manualmente.",
    deliveryUnknown: "O resultado não foi confirmado. Os controles permanecerão bloqueados até que o Hermes reconcilie a solicitação.", noLongerPending: "O Hermes não confirmou que a solicitação ainda está pendente.", rejectedResponse: "O Agent Control rejeitou a resposta.", responseFailed: "Não foi possível confirmar a resposta. Verifique a conexão e tente novamente.",
    stopUnknown: "Não foi possível confirmar a interrupção; a execução pode continuar no Hermes.", stopped: "Execução interrompida.",
  }, searchMeta: { agent: "Agente", history: "histórico", conversation: "Conversa do Hermes", sessionCount: "{{count}} sessões", workspace: "Workspace · {{count}} sessões", activeAutomation: "Automação ativa", pausedAutomation: "Automação pausada" } },
} as const;
