export const visionCopy = {
  es: {
    title: "Cámara", activate: "Activar cámara", inactive: "Cámara desactivada", close: "Cerrar cámara", model: "Modelo", activationHint: "El navegador solicitará permiso cuando pulses Activar cámara.", choose: "Elegir modo de cámara", changeMode: "Cambiar modo", onDemand: "Preguntar sobre la cámara", onDemandHint: "Pregunta por chat o por voz qué quieres saber sobre lo que ve la cámara. Esperará tu pregunta antes de analizar.", continuous: "Seguimiento automático", continuousHint: "Analiza al activar la cámara y comenta cambios sin que preguntes.",
    starting: "Abriendo cámara…", active: "Cámara activa", paused: "Cámara pausada", stop: "Apagar cámara", pause: "Pausar cámara", resume: "Reanudar cámara", device: "Cámara del dispositivo", defaultDevice: "Cámara predeterminada", cameraNumber: "Cámara", look: "Mirar ahora", analyzing: "Analizando…", question: "¿Qué quieres saber?", questionPlaceholder: "Por ejemplo: ¿qué tengo enfrente?", attach: "Adjuntar captura analizada", newCapture: "Tomar y adjuntar nueva captura", temporary: "Las capturas son temporales. Solo se guardan los hallazgos en texto; adjunta una captura si quieres conservarla.", continuousStatus: "El siguiente análisis comienza después del resultado y la pausa elegida.", observations: "Observaciones de cámara", earlier: "Ver anteriores", loading: "Cargando…", captured: "Captura", uncertainty: "No está claro", settings: "Configura el modelo y la frecuencia en Preferencias → Visión.",
    errors: { quota: "OpenAI alcanzó la cuota o el límite de solicitudes. Revisa tu cuenta y reanuda la cámara.", access: "OpenAI no permite usar el modelo de visión elegido con esta clave. Revisa el modelo en Preferencias.", timeout: "OpenAI no terminó el análisis a tiempo. No se repitió la solicitud. Reanuda para intentarlo con una captura nueva.", stale: "La captura es demasiado antigua. Reanuda para tomar una nueva.", unsupported: "Este navegador no permite usar la cámara.", permission: "Permite el acceso a la cámara en el navegador y vuelve a activarla.", unavailable: "La cámara no está disponible. Revisa si otra aplicación la está usando.", capture: "No se pudo tomar la captura. Inténtalo de nuevo.", analysis: "No se pudo completar el análisis. Reanuda la cámara para continuar.", busy: "Hay un análisis en curso. Espera su resultado.", configuration: "Configura una clave de OpenAI en Preferencias para activar la visión.", load: "No se pudo cargar la configuración o las observaciones de cámara." },
  },
  en: {
    title: "Camera", activate: "Activate camera", inactive: "Camera off", close: "Close camera", model: "Model", activationHint: "Your browser will ask for permission when you press Activate camera.", choose: "Choose camera mode", changeMode: "Change mode", onDemand: "Ask about the camera", onDemandHint: "Ask in chat or by voice what you want to know about the camera view. It waits for your question before analyzing.", continuous: "Automatic observation", continuousHint: "Analyze when the camera opens and comment on changes without waiting for a question.",
    starting: "Opening camera…", active: "Camera active", paused: "Camera paused", stop: "Turn camera off", pause: "Pause camera", resume: "Resume camera", device: "Device camera", defaultDevice: "Default camera", cameraNumber: "Camera", look: "Look now", analyzing: "Analyzing…", question: "What would you like to know?", questionPlaceholder: "For example: what is in front of me?", attach: "Attach analyzed capture", newCapture: "Take and attach a new capture", temporary: "Captures are temporary. Only text observations are saved; attach a capture to keep it.", continuousStatus: "The next analysis starts after the result and your selected interval.", observations: "Camera observations", earlier: "Show earlier", loading: "Loading…", captured: "Captured", uncertainty: "Uncertain", settings: "Choose the model and interval in Preferences → Vision.",
    errors: { quota: "OpenAI reached its quota or request limit. Check your account, then resume the camera.", access: "OpenAI does not allow the selected vision model with this key. Review your model in Preferences.", timeout: "OpenAI did not finish in time. The request was not repeated. Resume to try with a new capture.", stale: "The capture is too old. Resume to take a new one.", unsupported: "This browser does not support camera access.", permission: "Allow camera access in your browser, then activate it again.", unavailable: "The camera is unavailable. Check whether another application is using it.", capture: "Could not capture an image. Try again.", analysis: "The analysis could not finish. Resume the camera to continue.", busy: "An analysis is in progress. Wait for its result.", configuration: "Configure an OpenAI key in Preferences to activate vision.", load: "Could not load camera preferences or observations." },
  },
};
